# Generated by Django 3.2 on 2022-09-13 22:29

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='mechanic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=13)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(choices=[('lahore', 'lahore'), ('Karachi', 'Karachi'), ('Faislbad', 'Faislbad')], max_length=50)),
                ('lat', models.DecimalField(decimal_places=9, max_digits=12)),
                ('lang', models.DecimalField(decimal_places=9, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.FloatField()),
                ('image', models.FileField(default='', upload_to='static/images', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg'])])),
                ('company', models.CharField(default=None, max_length=50)),
                ('category', models.CharField(choices=[('motor cycle', 'motor cycle'), ('spare parts', 'spare parts'), ('electronic parts', 'electronic parts'), ('tyre', 'tyre')], max_length=50)),
                ('availability', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MotorCycle',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myapp.product')),
                ('model_no', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=20)),
                ('cc', models.CharField(choices=[('70', '70'), ('100', '100'), ('125', '125'), ('150', '150'), ('200', '200'), ('250', '250')], max_length=50)),
            ],
            bases=('myapp.product',),
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('shop_no', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('review', models.CharField(max_length=255)),
                ('rating', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop', to='myapp.shop'),
        ),
        migrations.CreateModel(
            name='order_detail',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('order_id', models.CharField(blank=True, max_length=20, null=True)),
                ('items', models.JSONField(default=dict)),
                ('total', models.FloatField(blank=True, default=None)),
                ('created_at', models.DateField(auto_now=True)),
                ('is_approve', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='delivery_address',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('phone_number', models.CharField(max_length=13)),
                ('address', models.CharField(max_length=150)),
                ('city', models.CharField(choices=[('lahore', 'lahore'), ('Karachi', 'Karachi'), ('Faislbad', 'Faislbad')], max_length=50)),
                ('delivery_instruction', models.CharField(blank=True, max_length=250, null=True)),
                ('deliver_date', models.DateField()),
                ('is_deliver', models.BooleanField(default=False)),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.order_detail')),
            ],
        ),
    ]
