# Generated by Django 3.2 on 2022-09-13 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bike_color',
            field=models.CharField(default='red', max_length=20),
        ),
        migrations.AlterField(
            model_name='order_detail',
            name='total',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.DeleteModel(
            name='MotorCycle',
        ),
    ]
