# Generated by Django 3.2 on 2022-09-14 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20220914_0401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery_address',
            name='deliver_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='delivery_address',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
