# Generated by Django 3.2 on 2022-09-21 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20220914_0504'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
