# Generated by Django 3.2 on 2022-09-27 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rating_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_detail',
            name='address',
            field=models.CharField(default=' ', max_length=150),
        ),
        migrations.AddField(
            model_name='order_detail',
            name='city',
            field=models.CharField(choices=[('lahore', 'lahore'), ('Karachi', 'Karachi'), ('Faislbad', 'Faislbad')], default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='order_detail',
            name='deliver_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order_detail',
            name='delivery_instruction',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='order_detail',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='order_detail',
            name='first_name',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='order_detail',
            name='is_deliver',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order_detail',
            name='last_name',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='order_detail',
            name='order_status',
            field=models.CharField(choices=[('Cancel', 'Cancel'), ('Pending', 'Pending'), ('Deliver', 'Deliver')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='order_detail',
            name='phone_number',
            field=models.CharField(default=None, max_length=13),
        ),
        migrations.AddField(
            model_name='order_detail',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='order_detail',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='delivery_address',
        ),
    ]
